CSS Parser: CSSParser::parseInValue
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parseInValue()
void CSSParser::parseInValue (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at, char & str_char, bool & pn, int str_size) private
 {
     pn = (((css_input[i] == '\n' || css_input[i] == '\r') && property_is_next(css_input,i+1)) || i == str_size-1);
     if(pn)
     {
         log("Added semicolon to the end of declaration",Warning);
     }
     std::cout << "Pin: " << pn << std::endl;
     if(is_token(css_input,i) || pn)
     {
         std::cout << "PIV " << css_input[i] << " Is Token"<< std::endl;
         if((css_input[i] == '{') && (cur_selector == "@import" ||
                                      cur_selector == "@charset" ||
                                      cur_selector == "@namespace"))
         {
             log("Unexpected character '" + std::string(1, css_input[i]) + "' in " + cur_selector, Error);
         }
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; ++i;
             afrom = PIV;
         }
         else if(css_input[i] == '"' || css_input[i] == '\'' ||
                 (css_input[i] == '(' && cur_sub_value == "url") )
         {
             str_char = (css_input[i] == '(') ? ')' : css_input[i];
             cur_string = css_input[i];
             astatus = PINSTR;
             afrom = PIV;
         }
         else if(css_input[i] == '(')
         {
             // function call or an open parenthesis in a calc() expression
             // url() is a special case that should have been handled above
             assert(cur_sub_value != "url");
             // cur_sub_value should contain the name of the function, if any
             cur_sub_value = CSSUtils::trim(cur_sub_value + "(");
             // set current function name and push it onto the stack
             cur_function = cur_sub_value;
             cur_function_arr.push_back(cur_sub_value);
             cur_sub_value_arr.push_back(cur_sub_value);
             cur_sub_value = "";
         }
         else if(css_input[i] == '\\')
         {
             cur_sub_value += unicode(css_input,i);
         }
         else if(css_input[i] == ';' || pn)
         {
             if(cur_selector.substr(0,1) == "@" &&
                at_rules.count(cur_selector.substr(1)) > 0 &&
                at_rules[cur_selector.substr(1)] == PIV)
             {
                 cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
                 astatus = PIS;
                 if(cur_selector == "@charset")
                 {
                      charset = cur_sub_value_arr[0];
                      add_token(CHARSET, charset);
                 }
                 else if(cur_selector == "@import")
                 {
                      std::string aimport = CSSUtils::build_value(cur_sub_value_arr);
                      add_token(IMPORT, aimport);
                      import.push_back(aimport);
                 }
                 else if(cur_selector == "@namespace")
                 {
                     namesp = CSSUtils::implode(" ",cur_sub_value_arr);
                     add_token(NAMESP, namesp);
                 }
                 cur_sub_value_arr.clear();
                 cur_sub_value = "";
                 cur_selector = "";
                 sel_separate = std::vector<int>();
             }
             else
             {
                 astatus = PIP;
             }
         }
         else if (css_input[i] == '!')
         {
             cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
             cur_sub_value = "!";
         }
         else if (css_input[i] == ',' || css_input[i] == ')')
         {
             // store the current subvalue, if any
             cur_sub_value = CSSUtils::trim(cur_sub_value);
             if(cur_sub_value != "")
             {
                 cur_sub_value_arr.push_back(cur_sub_value);
                 cur_sub_value = "";
             }
             bool drop = false;
             if (css_input[i] == ')')
             {
                 if (cur_function_arr.empty())
                 {
                     // No matching open parenthesis, drop this closing one
                     log("Unexpected closing parenthesis, dropping", Warning);
                     drop = true;
                 }
                 else
                 {
                     // Pop function from the stack
                     cur_function_arr.pop_back();
                     cur_function = cur_function_arr.empty() ? "" : cur_function_arr.back();
                 }
             }
             if (!drop) {
                 cur_sub_value_arr.push_back(std::string(1,css_input[i]));
             }
         }
         else if(css_input[i] != '}')
         {
             cur_sub_value += css_input[i];
         }
         if( (css_input[i] == '}' || css_input[i] == ';' || pn) && !cur_selector.empty())
         {
             // End of value: normalize, optimize and store property
             if(cur_at == "")
             {
                 cur_at = "standard";
             }
             // Kill all whitespace
             cur_at = CSSUtils::trim(cur_at);
             cur_selector = CSSUtils::trim(cur_selector);
             cur_value = CSSUtils::trim(cur_value);
             cur_property = CSSUtils::trim(cur_property);
             cur_sub_value = CSSUtils::trim(cur_sub_value);
             cur_property = CSSUtils::strtolower(cur_property);
             if(cur_sub_value != "")
             {
                 cur_sub_value_arr.push_back(cur_sub_value);
                 cur_sub_value = "";
             }
             // Check for leftover open parentheses
             if (!cur_function_arr.empty())
             {
                 std::vector<std::string>::reverse_iterator rit;
                 for (rit = cur_function_arr.rbegin(); rit != cur_function_arr.rend(); ++rit)
                 {
                     log("Closing parenthesis missing for '" + *rit + "', inserting", Warning);
                     cur_sub_value_arr.push_back(")");
                 }
             }
             cur_value = CSSUtils::build_value(cur_sub_value_arr);
             bool valid = (CSSProperties::instance()->contains(cur_property) &&
                           CSSProperties::instance()->levels(cur_property).find(css_level,0) != std::string::npos);
             if(1)
             {
                 //add(cur_at,cur_selector,cur_property,cur_value);
                 add_token(VALUE, cur_value);
             }
             if(!valid)
             {
                 log("Invalid property in " + CSSUtils::strtoupper(css_level) + ": " + cur_property,Warning);
             }
             //Split multiple selectors here if necessary
             cur_property = "";
             cur_sub_value_arr.clear();
             cur_value = "";
         }
         if(css_input[i] == '}')
         {
             explode_selectors();
             add_token(SEL_END, cur_selector);
             astatus = PIS;
             invalid_at = false;
             cur_selector = "";
         }
     }
     else if(!pn)
     {
         cur_sub_value += css_input[i];
         if(CSSUtils::ctype_space(css_input[i]))
         {
             if(CSSUtils::trim(cur_sub_value) != "")
             {
                 cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
             }
             cur_sub_value = "";
         }
     }
 }
References add_token(), at_rules, CSSUtils::build_value(), CHARSET, charset, CSSProperties::contains(), css_level, CSSUtils::ctype_space(), cur_at, cur_function, cur_function_arr, cur_property, cur_selector, cur_string, cur_sub_value, cur_sub_value_arr, cur_value, Error, explode_selectors(), CSSUtils::implode(), IMPORT, CSSProperties::instance(), is_token(), CSSProperties::levels(), log(), NAMESP, namesp, PIC, PINSTR, PIP, PIS, PIV, property_is_next(), CSSUtils::s_at(), SEL_END, sel_separate, CSSUtils::strtolower(), CSSUtils::strtoupper(), CSSUtils::trim(), unicode(), VALUE, and Warning.
Referenced by parse_css().