CSS Parser: CSSParser::parseInProperty
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parseInProperty()
void CSSParser::parseInProperty (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at) private
 {
     std::cout << "PIP Posistion: " << i << std::endl;
     if (is_token(css_input,i))
     {
         std::cout << "PIP " << css_input[i] << " Is Token"<< std::endl;
         if (css_input[i] == ':' || (css_input[i] == '=' && cur_property != ""))
         {
             astatus = PIV;
             bool valid = true || (CSSProperties::instance()->contains(cur_property) &&
                                   CSSProperties::instance()->levels(cur_property).find(css_level,0) != std::string::npos);
             if(valid) {
                 add_token(PROPERTY, cur_property);
             }
         }
         else if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*' && cur_property == "")
         {
             astatus = PIC; ++i;
             afrom = PIP;
         }
         else if(css_input[i] == '}')
         {
             explode_selectors();
             astatus = PIS;
             invalid_at = false;
             add_token(SEL_END, cur_selector);
             cur_selector = "";
             cur_property = "";
         }
         else if(css_input[i] == ';')
         {
             cur_property = "";
         }
         else if(css_input[i] == '\\')
         {
             cur_property += unicode(css_input,i);
         }
         else if(css_input[i] == '*')
         {
             // IE7 and below recognize properties that begin with '*'
             if (cur_property == "")
             {
                 cur_property += css_input[i];
                 log("IE7- hack detected: property name begins with '*'", Warning);
             }
         }
         else
         {
             log("Unexpected character '" + std::string(1, css_input[i]) + "'in property name", Error);
         }
     }
     else if(!CSSUtils::ctype_space(css_input[i]))
     {
         if(css_input[i] == '_' && cur_property == "")
         {
             // IE6 and below recognize properties that begin with '_'
             log("IE6 hack detected: property name begins with '_'", Warning);
         }
         // TODO: Check for invalid characters
         cur_property += css_input[i];
     }
     // TODO: Check for whitespace inside property names
 }
References add_token(), CSSProperties::contains(), css_level, CSSUtils::ctype_space(), cur_property, cur_selector, Error, explode_selectors(), CSSProperties::instance(), is_token(), CSSProperties::levels(), log(), PIC, PIP, PIS, PIV, PROPERTY, CSSUtils::s_at(), SEL_END, unicode(), and Warning.
Referenced by parse_css().