CSS Parser: CSSParser::parse_css
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parse_css()
void CSSParser::parse_css (std::string css_input)
 {
     reset_parser();
     css_input = CSSUtils::str_replace("\r\n","\n",css_input); // Replace newlines
     css_input += "\n";
 //     std::cout << "Css Input: " << css_input << std::endl;
     parse_status astatus = PIS, afrom;
     parse_status old_status = PIS;
     record_position(PIS, PIS, css_input, 0, true);
     std::string cur_comment;
     cur_sub_value_arr.clear();
     cur_function_arr.clear(); // Stack of nested function calls
     char str_char;
     bool str_in_str = false;
     bool invalid_at = false;
     bool pn = false;
     int str_size = css_input.length();
     for(int i = 0; i < str_size; ++i)
     {
         if(css_input[i] == '\n' || css_input[i] == '\r')
         {
             ++line;
         }
         // record current position for selected state transitions
         std::cout << "Current Posistion: "<< i << std::endl;
         if (old_status != astatus)
         {
             record_position(old_status, astatus, css_input, i);
         }
         old_status = astatus;
         switch(astatus)
         {
             /* Case in-at-block */
             case PAT:
                 parseInAtBlock(css_input, i, astatus, afrom);
                 break;
             /* Case in-selector */
             case PIS:
                 parseInSelector(css_input, i, astatus, afrom, invalid_at, str_char, str_size);
                 break;
             /* Case in-property */
             case PIP:
                 parseInProperty(css_input, i, astatus, afrom, invalid_at);
                 break;
             /* Case in-value */
             case PIV:
                 parseInValue(css_input, i, astatus, afrom, invalid_at, str_char, pn, str_size);
                 break;
             /* Case in-string */
             case PINSTR:
                 parseInString(css_input, i, astatus, afrom, str_char, str_in_str);
                 break;
             /* Case in-comment */
             case PIC:
                 parseInComment(css_input, i, astatus, afrom, cur_comment);
                 break;
         }
         std::cout << "Pre Status: " <<  ParseStatus[old_status] << " Current Status: " << ParseStatus[astatus]  << std::endl;
     }
     // validate that every selector start had its own selector end
     if (selector_nest_level != 0)
     {
         log("Unbalanced selector braces in style sheet", Error, line);
     }
 }
References cur_function_arr, cur_sub_value_arr, Error, line, log(), parseInAtBlock(), parseInComment(), parseInProperty(), parseInSelector(), parseInString(), parseInValue(), PAT, PIC, PINSTR, PIP, PIS, PIV, record_position(), reset_parser(), selector_nest_level, and CSSUtils::str_replace().