CSS Parser: CSSParser::parseInAtBlock
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parseInAtBlock()
void CSSParser::parseInAtBlock (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom) private
 {
     if(is_token(css_input,i))
     {
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; i += 2;
             afrom = PAT;
         }
         else if(css_input[i] == '{')
         {
             astatus = PIS;
             add_token(AT_START, cur_at);
         }
         else if(css_input[i] == ',')
         {
             cur_at = CSSUtils::trim(cur_at) + ",";
         }
         else if(css_input[i] == '\\')
         {
             cur_at += unicode(css_input,i);
         }
         else /*if((css_input[i] == '(') || (css_input[i] == ':') || (css_input[i] == ')') || (css_input[i] == '.'))*/
         {
             if(!CSSUtils::in_char_arr("():/.", css_input[i]))
             {
                 // Strictly speaking, these are only permitted in @media rules
                 log("Unexpected symbol '" + std::string(css_input, i, 1) + "' in @-rule", Warning);
             }
             cur_at += css_input[i];  /* append tokens after media selector */
         }
     }
     else
     {
         // Skip excess whitespace
         int lastpos = cur_at.length()-1;
         if(lastpos == -1 || !( (CSSUtils::ctype_space(cur_at[lastpos]) ||
                                (is_token(cur_at,lastpos) && cur_at[lastpos] == ',')) &&
                                CSSUtils::ctype_space(css_input[i])))
         {
             cur_at += css_input[i];
         }
     }
 }
References add_token(), AT_START, CSSUtils::ctype_space(), cur_at, CSSUtils::in_char_arr(), is_token(), log(), PAT, PIC, PIS, CSSUtils::s_at(), CSSUtils::trim(), unicode(), and Warning.
Referenced by parse_css().