CSS Parser: CSSParser::add_token
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
add_token()
void CSSParser::add_token (const token_type ttype, const std::string data, const bool force = false) private
 {
     token temp;
     temp.type = ttype;
     temp.pos = spos;
     temp.line = sline;
     temp.data = (ttype == COMMENT) ? data : CSSUtils::trim(data);
     csstokens.push_back(temp);
     if (ttype == SEL_START) selector_nest_level++;
     if (ttype == SEL_END) selector_nest_level--;
 }
References COMMENT, csstokens, CSSParser::token::data, CSSParser::token::line, CSSParser::token::pos, SEL_END, SEL_START, selector_nest_level, sline, spos, CSSUtils::trim(), and CSSParser::token::type.
Referenced by parseInAtBlock(), parseInComment(), parseInProperty(), parseInSelector(), and parseInValue().