CSS Parser: CSSParser::parseInString
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parseInString()
void CSSParser::parseInString (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, char & str_char, bool & str_in_str) private
 {
     if(str_char == ')' && (css_input[i] == '"' || css_input[i] == '\'') &&
        str_in_str == false && !CSSUtils::escaped(css_input,i))
     {
         str_in_str = true;
     }
     else if(str_char == ')' && (css_input[i] == '"' || css_input[i] == '\'') &&
             str_in_str == true && !CSSUtils::escaped(css_input,i))
     {
         str_in_str = false;
     }
     std::string temp_add = ""; temp_add += css_input[i];
     if( (css_input[i] == '\n' || css_input[i] == '\r') &&
         !(css_input[i-1] == '\\' && !CSSUtils::escaped(css_input,i-1)) )
     {
         temp_add = "\\A ";
         log("Fixed incorrect newline in string",Warning);
     }
     if (!(str_char == ')' &&
           CSSUtils::char2str(css_input[i]).find_first_of(" \n\t\r\0xb") != std::string::npos && !str_in_str))
     {
         cur_string += temp_add;
     }
     if(css_input[i] == str_char && !CSSUtils::escaped(css_input,i) && str_in_str == false)
     {
         astatus = afrom;
         if (cur_function == "" &&
             cur_string.find_first_of(" \n\t\r\0xb") == std::string::npos &&
             cur_property != "content" && cur_sub_value != "format")
         {
             // If the string is not inside a function call, contains no whitespace,
             // and the current property is not 'content', it may be safe to remove quotes.
             // TODO: Are there any properties other than 'content' where this is unsafe?
             // TODO: What if the string contains a comma or slash, and the property is a list or shorthand?
             if (str_char == '"' || str_char == '\'')
             {
                 // If the string is in double or single quotes, remove them
                 // FIXME: once url() is handled separately, this may always be the case.
                 cur_string = cur_string.substr(1, cur_string.length() - 2);
             } else if (cur_string.length() > 3 && (cur_string[1] == '"' || cur_string[1] == '\'')) /* () */
             {
                 cur_string = cur_string[0] + cur_string.substr(2, cur_string.length() - 4) + cur_string[cur_string.length()-1];
             }
         }
         if(afrom == PIV)
         {
             cur_sub_value += cur_string;
         }
         else if(afrom == PIS)
         {
             cur_selector += cur_string;
         }
     }
 }
References CSSUtils::char2str(), cur_function, cur_property, cur_selector, cur_string, cur_sub_value, CSSUtils::escaped(), log(), PIS, PIV, and Warning.
Referenced by parse_css().