CSS Parser: CSSParser::parseInSelector
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
parseInSelector()
void CSSParser::parseInSelector (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at, char & str_char, int str_size) private
 {
     if(is_token(css_input,i))
     {
         // if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*' &&
         // trim(cur_selector) == "") selector as dep doesn't make any sense here, huh?
 //         std::cout << "Css input: " << css_input[i] << std::endl;
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; ++i;
             afrom = PIS;
         }
         else if(css_input[i] == '@' && CSSUtils::trim(cur_selector) == "")
         {
             // Check for at-rule
             invalid_at = true;
             for(std::map<std::string,parse_status>::iterator j = at_rules.begin(); j != at_rules.end(); ++j )
             {
                 if(CSSUtils::strtolower(css_input.substr(i+1,j->first.length())) == j->first)
                 {
                     (j->second == PAT) ? cur_at = "@" + j->first : cur_selector = "@" + j->first;
                     astatus = j->second;
                     i += j->first.length();
                     invalid_at = false;
                 }
             }
             if (invalid_at)
             {
                 cur_selector = "@";
                 std::string invalid_at_name = "";
                 for(int j = i+1; j < str_size; ++j)
                 {
                     if(!CSSUtils::ctype_alpha(css_input[j]))
                     {
                         return;
                     }
                     invalid_at_name += css_input[j];
                 }
                 log("Invalid @-rule: " + invalid_at_name + " (removed)",Warning);
             }
         }
         else if(css_input[i] == '"' || css_input[i] == '\'')
         {
             cur_string = css_input[i];
             astatus = PINSTR;
             str_char = css_input[i];
             afrom = PIS;
         }
         else if(invalid_at && css_input[i] == ';')
         {
             invalid_at = false;
             astatus = PIS;
         }
         else if (css_input[i] == '{')
         {
             astatus = PIP;
             add_token(SEL_START, cur_selector);
         }
         else if (css_input[i] == '}')
         {
             add_token(AT_END, cur_at);
             cur_at = "";
             cur_selector = "";
             sel_separate = std::vector<int>();
         }
         else if(css_input[i] == ',')
         {
             cur_selector = CSSUtils::trim(cur_selector) + ",";
             sel_separate.push_back(cur_selector.length());
         }
         else if (css_input[i] == '\\')
         {
             cur_selector += unicode(css_input,i);
         }
         // remove unnecessary universal selector,  FS#147
         else if(!(css_input[i] == '*' && (CSSUtils::s_at(css_input,i+1) == '.' || CSSUtils::s_at(css_input,i+1) == '[' || CSSUtils::s_at(css_input,i+1) == ':' || CSSUtils::s_at(css_input,i+1) == '#')))
         {
             cur_selector += css_input[i];
         }
     }
     else
     {
         int lastpos = cur_selector.length()-1;
         if((lastpos == -1) || !( (CSSUtils::ctype_space(cur_selector[lastpos]) ||
                                   (is_token(cur_selector,lastpos) && cur_selector[lastpos] == ',')) &&
                                  CSSUtils::ctype_space(css_input[i])))
         {
             cur_selector += css_input[i];
         }
     }
 }
References add_token(), AT_END, at_rules, CSSUtils::ctype_alpha(), CSSUtils::ctype_space(), cur_at, cur_selector, cur_string, is_token(), log(), PAT, PIC, PINSTR, PIP, PIS, CSSUtils::s_at(), sel_separate, SEL_START, CSSUtils::strtolower(), CSSUtils::trim(), unicode(), and Warning.
Referenced by parse_css().