CSS Parser: CSSParser::serialize_css
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
serialize_css()
std::string CSSParser::serialize_css (std::string filename = "", bool tostdout = true)
 {
     if(charset == "" && namesp == "" && import.empty() && csstokens.empty())
     {
         std::cout << "Warning: empty CSS output!" << std::endl;
     }
     std::ofstream file_output;
     if(filename != "")
     {
          file_output.open(filename.c_str(),std::ios::binary);
          if(file_output.bad())
          {
              std::cout << "Error when trying to save the output file!" << std::endl;
              return "";
          }
     }
     std::stringstream output;
     int lvl = 0;
     std::string indent = "";
     for (int i = 0; i < csstokens.size(); ++i)
     {
         switch (csstokens[i].type)
         {
             case CHARSET:
                 output << "@charset " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case IMPORT:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << "@import " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case NAMESP:
                 output << "@namespace " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case AT_START:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << csstemplate[1];
                 lvl++;
                 break;
             case SEL_START:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << csstemplate[3];
                 lvl++;
                 break;
             case PROPERTY:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << ":" << csstemplate[5];
                 break;
             case VALUE:
                 output << csstokens[i].data << csstemplate[6];
                 break;
             case SEL_END:
                 lvl--; if (lvl < 0) lvl = 0;
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent + csstemplate[7];
                 if(_seeknocomment(i, 1) != AT_END) output << csstemplate[8];
                 break;
             case AT_END:
                 lvl--; if (lvl < 0) lvl = 0;
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << csstemplate[13] << indent << csstemplate[9];
                 break;
             case COMMENT:
                 output << csstemplate[11] <<  "/*" << csstokens[i].data << "*/" << csstemplate[12];
                 break;
             case CSS_END:
                 break;
         }
     }
     std::string output_string = CSSUtils::trim(output.str());
     if(tostdout)
     {
         std::cout << output_string << "\n";
     }
     if(filename != "")
     {
         file_output << output_string;
         file_output.close();
     }
     return output_string;
 }
References _seeknocomment(), AT_END, AT_START, CHARSET, charset, COMMENT, CSS_END, csstemplate, csstokens, IMPORT, CSSUtils::indent(), NAMESP, namesp, PROPERTY, SEL_END, SEL_START, CSSUtils::trim(), and VALUE.