CSS Parser: CSSParser::unicode
_seeknocomment
add_token
at_rules
charset
css_level
CSSParser
csstemplate
csstokens
cur_at
cur_function
cur_function_arr
cur_property
cur_selector
cur_string
cur_sub_value
cur_sub_value_arr
cur_value
explode_selectors
get_charset
get_import
get_logs
get_namespace
get_next_token
get_parse_errors
get_parse_info
get_parse_warnings
get_type_name
import
is_token
line
log
logs
message_type
namesp
parse_css
parse_status
parseInAtBlock
parseInComment
parseInProperty
parseInSelector
parseInString
parseInValue
property_is_next
record_position
reset_parser
sel_separate
selector_nest_level
serialize_css
set_csstokens
set_level
sline
spos
token_ptr
token_type
token_type_names
tokens
unicode
unicode()
std::string CSSParser::unicode (std::string & istring, int & i) private
 {
     ++i;
     std::string add = "";
     bool replaced = false;
     while(i < istring.length() && (CSSUtils::ctype_xdigit(istring[i]) ||
                                    CSSUtils::ctype_space(istring[i])) && add.length()< 6)
     {
         add += istring[i];
         if(CSSUtils::ctype_space(istring[i])) {
             break;
         }
         i++;
     }
     if ((CSSUtils::hexdec(add) > 47 && CSSUtils::hexdec(add) < 58) ||
         (CSSUtils::hexdec(add) > 64 && CSSUtils::hexdec(add) < 91) ||
         (CSSUtils::hexdec(add) > 96 && CSSUtils::hexdec(add) < 123))
     {
         std::string msg = "Replaced unicode notation: Changed \\" + CSSUtils::rtrim(add) + " to ";
         add = static_cast<int>(CSSUtils::hexdec(add));
         msg += add;
         log(msg,Information);
         replaced = true;
     } else {
         add = CSSUtils::trim("\\" + add);
     }
     if ((CSSUtils::ctype_xdigit(istring[i+1]) && CSSUtils::ctype_space(istring[i])
          && !replaced) || !CSSUtils::ctype_space(istring[i]))
     {
         i--;
     }
     if (1) {
         return add;
     }
     return "";
 }
References CSSUtils::ctype_space(), CSSUtils::ctype_xdigit(), CSSUtils::hexdec(), Information, log(), CSSUtils::rtrim(), and CSSUtils::trim().
Referenced by parseInAtBlock(), parseInProperty(), parseInSelector(), and parseInValue().