CSS Parser: CSSParser Class Reference
CSSParser Class Reference
#include <CSSParser.h>
Classes
struct message
struct token
Public Types
enum message_type { Information , Warning , Error }
enum parse_status {
PIS , PIP , PIV , PINSTR ,
PIC , PAT
}
enum token_type {
CHARSET , IMPORT , NAMESP , AT_START ,
AT_END , SEL_START , SEL_END , PROPERTY ,
VALUE , COMMENT , CSS_END
}
Public Member Functions
CSSParser ()
std::string get_charset ()
std::vector< std::string > get_import ()
std::string get_namespace ()
token get_next_token (int start_ptr=-1)
std::vector< std::string > get_parse_errors ()
std::vector< std::string > get_parse_info ()
std::vector< std::string > get_parse_warnings ()
std::string get_type_name (token_type t)
void parse_css (std::string css_input)
void reset_parser ()
std::string serialize_css (std::string filename="", bool tostdout=true)
void set_csstokens (const std::vector< token > &ntokens)
void set_level (std::string level="CSS3.0")
Private Member Functions
int _seeknocomment (const int key, const int move)
void add_token (const token_type ttype, const std::string data, const bool force=false)
void explode_selectors ()
std::vector< std::string > get_logs (message_type t)
bool is_token (std::string &istring, const int i)
void log (const std::string msg, const message_type type, int iline=0)
void parseInAtBlock (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom)
void parseInComment (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom, std::string &cur_comment)
void parseInProperty (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom, bool &invalid_at)
void parseInSelector (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom, bool &invalid_at, char &str_char, int str_size)
void parseInString (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom, char &str_char, bool &str_in_str)
void parseInValue (std::string &css_input, int &i, parse_status &astatus, parse_status &afrom, bool &invalid_at, char &str_char, bool &pn, int str_size)
void record_position (parse_status old_status, parse_status new_status, std::string &css_input, int i, bool force=false)
std::string unicode (std::string &istring, int &i)
Static Private Member Functions
static bool property_is_next (std::string istring, int pos)
Private Attributes
std::map< std::string, parse_status > at_rules
std::string charset
std::string css_level
std::vector< std::string > csstemplate
std::vector< token > csstokens
std::string cur_at
std::string cur_function
std::vector< std::string > cur_function_arr
std::string cur_property
std::string cur_selector
std::string cur_string
std::string cur_sub_value
std::vector< std::string > cur_sub_value_arr
std::string cur_value
std::vector< std::string > import
int line
std::map< int, std::vector< message > > logs
std::string namesp
std::vector< int > sel_separate
int selector_nest_level
int sline
int spos
int token_ptr
std::vector< std::string > token_type_names
std::string tokens
Detailed Description
Class Documentation
CSSParser::message
struct CSSParser::message
Class Members
string m
message_type t
CSSParser::token
struct CSSParser::token
Class Members
string data
int line
int pos
token_type type
Member Enumeration Documentation
message_type
enum CSSParser::message_type
Enumerator
Information
Warning
Error
     {
         Information,Warning,Error
     };
parse_status
enum CSSParser::parse_status
Enumerator
PIS
PIP
PIV
PINSTR
PIC
PAT
     {
         PIS, PIP, PIV, PINSTR, PIC, PAT
     };
token_type
enum CSSParser::token_type
Enumerator
CHARSET
IMPORT
NAMESP
AT_START
AT_END
SEL_START
SEL_END
PROPERTY
VALUE
COMMENT
CSS_END
     {
         CHARSET, IMPORT, NAMESP, AT_START, AT_END, SEL_START, SEL_END, PROPERTY, VALUE, COMMENT, CSS_END
     };
Constructor & Destructor Documentation
CSSParser()
CSSParser::CSSParser ()
 {
     tokens = "{};:()@='\"/,\\!$%&*+.<>?[]^`|~";
     // Used for serializing parsed css
     csstemplate.push_back("    ");    //  0 - standard indentation
     csstemplate.push_back(" {\n");    //  1 - bracket after @-rule
     csstemplate.push_back("");        //  2 - unused
     csstemplate.push_back(" {\n");    //  3 - bracket after selector was "\n{\n"
     csstemplate.push_back("");        //  4 - unused
     csstemplate.push_back("");        //  5 - string after property before value
     csstemplate.push_back(";\n");     //  6 - string after value
     csstemplate.push_back("}");       //  7 - closing bracket - selector
     csstemplate.push_back("\n\n");    //  8 - space between blocks {...}
     csstemplate.push_back("}\n\n");   //  9 - closing bracket @-rule
     csstemplate.push_back("");        // 10 - unused
     csstemplate.push_back("");        // 11 - before comment
     csstemplate.push_back("\n");      // 12 - after comment
     csstemplate.push_back("\n");      // 13 - after last line @-rule
     // at_rule to parser state map
     at_rules["page"] = PIS;
     at_rules["font-face"] = PIS;
     at_rules["charset"] = PIV;
     at_rules["import"] = PIV;
     at_rules["namespace"] = PIV;
     at_rules["media"] = PAT;
     at_rules["keyframes"] = PAT;
     at_rules["supports"] = PAT;
     at_rules["-moz-keyframes"] = PAT;
     at_rules["-ms-keyframes"] = PAT;
     at_rules["-o-keyframes"] = PAT;
     at_rules["-webkit-keyframes"] = PAT;
     // descriptive names for each token type
     token_type_names.push_back("CHARSET");
     token_type_names.push_back("IMPORT");
     token_type_names.push_back("NAMESP");
     token_type_names.push_back("AT_START");
     token_type_names.push_back("AT_END");
     token_type_names.push_back("SEL_START");
     token_type_names.push_back("SEL_END");
     token_type_names.push_back("PROPERTY");
     token_type_names.push_back("VALUE");
     token_type_names.push_back("COMMENT");
     token_type_names.push_back("CSS_END");
     css_level = "CSS3.0";
 }
References at_rules, css_level, csstemplate, PAT, PIS, PIV, token_type_names, and tokens.
Member Function Documentation
_seeknocomment()
int CSSParser::_seeknocomment (const int key, const int move) private
 {
     int go = (move > 0) ? 1 : -1;
     for (int i = key + 1; abs(key-i)-1 < abs(move); i += go)
     {
         if (i < 0 || i >= csstokens.size()) {
             return -1;
         }
         if (csstokens[i].type == COMMENT) {
             move += 1;
             continue;
         }
         return csstokens[i].type;
     }
     // FIXME: control can reach end of non-void function
     return -1;
 }
References COMMENT, and csstokens.
Referenced by serialize_css().
add_token()
void CSSParser::add_token (const token_type ttype, const std::string data, const bool force = false) private
 {
     token temp;
     temp.type = ttype;
     temp.pos = spos;
     temp.line = sline;
     temp.data = (ttype == COMMENT) ? data : CSSUtils::trim(data);
     csstokens.push_back(temp);
     if (ttype == SEL_START) selector_nest_level++;
     if (ttype == SEL_END) selector_nest_level--;
 }
References COMMENT, csstokens, CSSParser::token::data, CSSParser::token::line, CSSParser::token::pos, SEL_END, SEL_START, selector_nest_level, sline, spos, CSSUtils::trim(), and CSSParser::token::type.
Referenced by parseInAtBlock(), parseInComment(), parseInProperty(), parseInSelector(), and parseInValue().
explode_selectors()
void CSSParser::explode_selectors () private
 {
     sel_separate = std::vector<int>();
 }
References sel_separate.
Referenced by parseInProperty(), and parseInValue().
get_charset()
std::string CSSParser::get_charset ()
 {
     return charset;
 }
References charset.
Referenced by main().
get_import()
std::vector< std::string > CSSParser::get_import ()
 {
     return import;
 }
Referenced by main().
get_logs()
std::vector< std::string > CSSParser::get_logs (CSSParser::message_type mt) private
 {
     std::vector<std::string> res;
     if(logs.size() > 0)
     {
         for(std::map<int, std::vector<message> >::iterator j = logs.begin(); j != logs.end(); j++ )
         {
             for(int i = 0; i < j->second.size(); ++i)
             {
                 if (j->second[i].t == mt) {
                     res.push_back(std::to_string(j->first) + ": " + j->second[i].m);
                 }
             }
         }
     }
     return res;
 }
References logs.
Referenced by get_parse_errors(), get_parse_info(), and get_parse_warnings().
get_namespace()
std::string CSSParser::get_namespace ()
 {
     return namesp;
 }
References namesp.
Referenced by main().
get_next_token()
CSSParser::token CSSParser::get_next_token (int start_ptr = -1)
 {
     if ((start_ptr >= 0) && (start_ptr < csstokens.size()))
     {
         token_ptr = start_ptr;
     }
     token atoken;
     atoken.type = CSS_END;
     atoken.data = "";
     if (token_ptr < csstokens.size())
     {
         atoken = csstokens[token_ptr];
         token_ptr++;
     }
     return atoken;
 }
References CSS_END, csstokens, CSSParser::token::data, token_ptr, and CSSParser::token::type.
Referenced by main().
get_parse_errors()
std::vector< std::string > CSSParser::get_parse_errors ()
 {
     return get_logs(CSSParser::Error);
 }
References Error, and get_logs().
Referenced by main().
get_parse_info()
std::vector< std::string > CSSParser::get_parse_info ()
 {
     return get_logs(CSSParser::Information);
 }
References get_logs(), and Information.
Referenced by main().
get_parse_warnings()
std::vector< std::string > CSSParser::get_parse_warnings ()
 {
     return get_logs(CSSParser::Warning);
 }
References get_logs(), and Warning.
Referenced by main().
get_type_name()
std::string CSSParser::get_type_name (CSSParser::token_type t)
 {
     return token_type_names[t];
 }
References token_type_names.
Referenced by main().
is_token()
bool CSSParser::is_token (std::string & istring, const int i) private
 {
     return (CSSUtils::in_str_array(tokens, istring[i]) && !CSSUtils::escaped(istring,i));
 }
References CSSUtils::escaped(), CSSUtils::in_str_array(), and tokens.
Referenced by parseInAtBlock(), parseInProperty(), parseInSelector(), and parseInValue().
log()
void CSSParser::log (const std::string msg, const message_type type, int iline = 0) private
 {
     message new_msg;
     new_msg.m = msg;
     new_msg.t = type;
     if(iline == 0)
     {
         iline = line;
     }
     if(logs.count(line) > 0)
     {
         for(int i = 0; i < logs[line].size(); ++i)
         {
             if(logs[line][i].m == new_msg.m && logs[line][i].t == new_msg.t)
             {
                 return;
             }
         }
     }
     logs[line].push_back(new_msg);
 }
References line, logs, CSSParser::message::m, and CSSParser::message::t.
Referenced by parse_css(), parseInAtBlock(), parseInProperty(), parseInSelector(), parseInString(), parseInValue(), and unicode().
parse_css()
void CSSParser::parse_css (std::string css_input)
 {
     reset_parser();
     css_input = CSSUtils::str_replace("\r\n","\n",css_input); // Replace newlines
     css_input += "\n";
 //     std::cout << "Css Input: " << css_input << std::endl;
     parse_status astatus = PIS, afrom;
     parse_status old_status = PIS;
     record_position(PIS, PIS, css_input, 0, true);
     std::string cur_comment;
     cur_sub_value_arr.clear();
     cur_function_arr.clear(); // Stack of nested function calls
     char str_char;
     bool str_in_str = false;
     bool invalid_at = false;
     bool pn = false;
     int str_size = css_input.length();
     for(int i = 0; i < str_size; ++i)
     {
         if(css_input[i] == '\n' || css_input[i] == '\r')
         {
             ++line;
         }
         // record current position for selected state transitions
         std::cout << "Current Posistion: "<< i << std::endl;
         if (old_status != astatus)
         {
             record_position(old_status, astatus, css_input, i);
         }
         old_status = astatus;
         switch(astatus)
         {
             /* Case in-at-block */
             case PAT:
                 parseInAtBlock(css_input, i, astatus, afrom);
                 break;
             /* Case in-selector */
             case PIS:
                 parseInSelector(css_input, i, astatus, afrom, invalid_at, str_char, str_size);
                 break;
             /* Case in-property */
             case PIP:
                 parseInProperty(css_input, i, astatus, afrom, invalid_at);
                 break;
             /* Case in-value */
             case PIV:
                 parseInValue(css_input, i, astatus, afrom, invalid_at, str_char, pn, str_size);
                 break;
             /* Case in-string */
             case PINSTR:
                 parseInString(css_input, i, astatus, afrom, str_char, str_in_str);
                 break;
             /* Case in-comment */
             case PIC:
                 parseInComment(css_input, i, astatus, afrom, cur_comment);
                 break;
         }
         std::cout << "Pre Status: " <<  ParseStatus[old_status] << " Current Status: " << ParseStatus[astatus]  << std::endl;
     }
     // validate that every selector start had its own selector end
     if (selector_nest_level != 0)
     {
         log("Unbalanced selector braces in style sheet", Error, line);
     }
 }
References cur_function_arr, cur_sub_value_arr, Error, line, log(), parseInAtBlock(), parseInComment(), parseInProperty(), parseInSelector(), parseInString(), parseInValue(), ParseStatus, PAT, PIC, PINSTR, PIP, PIS, PIV, record_position(), reset_parser(), selector_nest_level, and CSSUtils::str_replace().
Referenced by main().
parseInAtBlock()
void CSSParser::parseInAtBlock (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom) private
 {
     if(is_token(css_input,i))
     {
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; i += 2;
             afrom = PAT;
         }
         else if(css_input[i] == '{')
         {
             astatus = PIS;
             add_token(AT_START, cur_at);
         }
         else if(css_input[i] == ',')
         {
             cur_at = CSSUtils::trim(cur_at) + ",";
         }
         else if(css_input[i] == '\\')
         {
             cur_at += unicode(css_input,i);
         }
         else /*if((css_input[i] == '(') || (css_input[i] == ':') || (css_input[i] == ')') || (css_input[i] == '.'))*/
         {
             if(!CSSUtils::in_char_arr("():/.", css_input[i]))
             {
                 // Strictly speaking, these are only permitted in @media rules
                 log("Unexpected symbol '" + std::string(css_input, i, 1) + "' in @-rule", Warning);
             }
             cur_at += css_input[i];  /* append tokens after media selector */
         }
     }
     else
     {
         // Skip excess whitespace
         int lastpos = cur_at.length()-1;
         if(lastpos == -1 || !( (CSSUtils::ctype_space(cur_at[lastpos]) ||
                                (is_token(cur_at,lastpos) && cur_at[lastpos] == ',')) &&
                                CSSUtils::ctype_space(css_input[i])))
         {
             cur_at += css_input[i];
         }
     }
 }
References add_token(), AT_START, CSSUtils::ctype_space(), cur_at, CSSUtils::in_char_arr(), is_token(), log(), PAT, PIC, PIS, CSSUtils::s_at(), CSSUtils::trim(), unicode(), and Warning.
Referenced by parse_css().
parseInComment()
void CSSParser::parseInComment (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, std::string & cur_comment) private
 {
     if(css_input[i] == '*' && CSSUtils::s_at(css_input,i+1) == '/')
     {
         astatus = afrom;
         ++i;
         add_token(COMMENT, cur_comment);
         cur_comment = "";
     }
     else
     {
         cur_comment += css_input[i];
     }
 }
References add_token(), COMMENT, and CSSUtils::s_at().
Referenced by parse_css().
parseInProperty()
void CSSParser::parseInProperty (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at) private
 {
     std::cout << "PIP Posistion: " << i << std::endl;
     if (is_token(css_input,i))
     {
         std::cout << "PIP " << css_input[i] << " Is Token"<< std::endl;
         if (css_input[i] == ':' || (css_input[i] == '=' && cur_property != ""))
         {
             astatus = PIV;
             bool valid = true || (CSSProperties::instance()->contains(cur_property) &&
                                   CSSProperties::instance()->levels(cur_property).find(css_level,0) != std::string::npos);
             if(valid) {
                 add_token(PROPERTY, cur_property);
             }
         }
         else if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*' && cur_property == "")
         {
             astatus = PIC; ++i;
             afrom = PIP;
         }
         else if(css_input[i] == '}')
         {
             explode_selectors();
             astatus = PIS;
             invalid_at = false;
             add_token(SEL_END, cur_selector);
             cur_selector = "";
             cur_property = "";
         }
         else if(css_input[i] == ';')
         {
             cur_property = "";
         }
         else if(css_input[i] == '\\')
         {
             cur_property += unicode(css_input,i);
         }
         else if(css_input[i] == '*')
         {
             // IE7 and below recognize properties that begin with '*'
             if (cur_property == "")
             {
                 cur_property += css_input[i];
                 log("IE7- hack detected: property name begins with '*'", Warning);
             }
         }
         else
         {
             log("Unexpected character '" + std::string(1, css_input[i]) + "'in property name", Error);
         }
     }
     else if(!CSSUtils::ctype_space(css_input[i]))
     {
         if(css_input[i] == '_' && cur_property == "")
         {
             // IE6 and below recognize properties that begin with '_'
             log("IE6 hack detected: property name begins with '_'", Warning);
         }
         // TODO: Check for invalid characters
         cur_property += css_input[i];
     }
     // TODO: Check for whitespace inside property names
 }
References add_token(), CSSProperties::contains(), css_level, CSSUtils::ctype_space(), cur_property, cur_selector, Error, explode_selectors(), CSSProperties::instance(), is_token(), CSSProperties::levels(), log(), PIC, PIP, PIS, PIV, PROPERTY, CSSUtils::s_at(), SEL_END, unicode(), and Warning.
Referenced by parse_css().
parseInSelector()
void CSSParser::parseInSelector (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at, char & str_char, int str_size) private
 {
     if(is_token(css_input,i))
     {
         // if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*' &&
         // trim(cur_selector) == "") selector as dep doesn't make any sense here, huh?
 //         std::cout << "Css input: " << css_input[i] << std::endl;
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; ++i;
             afrom = PIS;
         }
         else if(css_input[i] == '@' && CSSUtils::trim(cur_selector) == "")
         {
             // Check for at-rule
             invalid_at = true;
             for(std::map<std::string,parse_status>::iterator j = at_rules.begin(); j != at_rules.end(); ++j )
             {
                 if(CSSUtils::strtolower(css_input.substr(i+1,j->first.length())) == j->first)
                 {
                     (j->second == PAT) ? cur_at = "@" + j->first : cur_selector = "@" + j->first;
                     astatus = j->second;
                     i += j->first.length();
                     invalid_at = false;
                 }
             }
             if (invalid_at)
             {
                 cur_selector = "@";
                 std::string invalid_at_name = "";
                 for(int j = i+1; j < str_size; ++j)
                 {
                     if(!CSSUtils::ctype_alpha(css_input[j]))
                     {
                         return;
                     }
                     invalid_at_name += css_input[j];
                 }
                 log("Invalid @-rule: " + invalid_at_name + " (removed)",Warning);
             }
         }
         else if(css_input[i] == '"' || css_input[i] == '\'')
         {
             cur_string = css_input[i];
             astatus = PINSTR;
             str_char = css_input[i];
             afrom = PIS;
         }
         else if(invalid_at && css_input[i] == ';')
         {
             invalid_at = false;
             astatus = PIS;
         }
         else if (css_input[i] == '{')
         {
             astatus = PIP;
             add_token(SEL_START, cur_selector);
         }
         else if (css_input[i] == '}')
         {
             add_token(AT_END, cur_at);
             cur_at = "";
             cur_selector = "";
             sel_separate = std::vector<int>();
         }
         else if(css_input[i] == ',')
         {
             cur_selector = CSSUtils::trim(cur_selector) + ",";
             sel_separate.push_back(cur_selector.length());
         }
         else if (css_input[i] == '\\')
         {
             cur_selector += unicode(css_input,i);
         }
         // remove unnecessary universal selector,  FS#147
         else if(!(css_input[i] == '*' && (CSSUtils::s_at(css_input,i+1) == '.' || CSSUtils::s_at(css_input,i+1) == '[' || CSSUtils::s_at(css_input,i+1) == ':' || CSSUtils::s_at(css_input,i+1) == '#')))
         {
             cur_selector += css_input[i];
         }
     }
     else
     {
         int lastpos = cur_selector.length()-1;
         if((lastpos == -1) || !( (CSSUtils::ctype_space(cur_selector[lastpos]) ||
                                   (is_token(cur_selector,lastpos) && cur_selector[lastpos] == ',')) &&
                                  CSSUtils::ctype_space(css_input[i])))
         {
             cur_selector += css_input[i];
         }
     }
 }
References add_token(), AT_END, at_rules, CSSUtils::ctype_alpha(), CSSUtils::ctype_space(), cur_at, cur_selector, cur_string, is_token(), log(), PAT, PIC, PINSTR, PIP, PIS, CSSUtils::s_at(), sel_separate, SEL_START, CSSUtils::strtolower(), CSSUtils::trim(), unicode(), and Warning.
Referenced by parse_css().
parseInString()
void CSSParser::parseInString (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, char & str_char, bool & str_in_str) private
 {
     if(str_char == ')' && (css_input[i] == '"' || css_input[i] == '\'') &&
        str_in_str == false && !CSSUtils::escaped(css_input,i))
     {
         str_in_str = true;
     }
     else if(str_char == ')' && (css_input[i] == '"' || css_input[i] == '\'') &&
             str_in_str == true && !CSSUtils::escaped(css_input,i))
     {
         str_in_str = false;
     }
     std::string temp_add = ""; temp_add += css_input[i];
     if( (css_input[i] == '\n' || css_input[i] == '\r') &&
         !(css_input[i-1] == '\\' && !CSSUtils::escaped(css_input,i-1)) )
     {
         temp_add = "\\A ";
         log("Fixed incorrect newline in string",Warning);
     }
     if (!(str_char == ')' &&
           CSSUtils::char2str(css_input[i]).find_first_of(" \n\t\r\0xb") != std::string::npos && !str_in_str))
     {
         cur_string += temp_add;
     }
     if(css_input[i] == str_char && !CSSUtils::escaped(css_input,i) && str_in_str == false)
     {
         astatus = afrom;
         if (cur_function == "" &&
             cur_string.find_first_of(" \n\t\r\0xb") == std::string::npos &&
             cur_property != "content" && cur_sub_value != "format")
         {
             // If the string is not inside a function call, contains no whitespace,
             // and the current property is not 'content', it may be safe to remove quotes.
             // TODO: Are there any properties other than 'content' where this is unsafe?
             // TODO: What if the string contains a comma or slash, and the property is a list or shorthand?
             if (str_char == '"' || str_char == '\'')
             {
                 // If the string is in double or single quotes, remove them
                 // FIXME: once url() is handled separately, this may always be the case.
                 cur_string = cur_string.substr(1, cur_string.length() - 2);
             } else if (cur_string.length() > 3 && (cur_string[1] == '"' || cur_string[1] == '\'')) /* () */
             {
                 cur_string = cur_string[0] + cur_string.substr(2, cur_string.length() - 4) + cur_string[cur_string.length()-1];
             }
         }
         if(afrom == PIV)
         {
             cur_sub_value += cur_string;
         }
         else if(afrom == PIS)
         {
             cur_selector += cur_string;
         }
     }
 }
References CSSUtils::char2str(), cur_function, cur_property, cur_selector, cur_string, cur_sub_value, CSSUtils::escaped(), log(), PIS, PIV, and Warning.
Referenced by parse_css().
parseInValue()
void CSSParser::parseInValue (std::string & css_input, int & i, parse_status & astatus, parse_status & afrom, bool & invalid_at, char & str_char, bool & pn, int str_size) private
 {
     pn = (((css_input[i] == '\n' || css_input[i] == '\r') && property_is_next(css_input,i+1)) || i == str_size-1);
     if(pn)
     {
         log("Added semicolon to the end of declaration",Warning);
     }
     std::cout << "Pin: " << pn << std::endl;
     if(is_token(css_input,i) || pn)
     {
         std::cout << "PIV " << css_input[i] << " Is Token"<< std::endl;
         if((css_input[i] == '{') && (cur_selector == "@import" ||
                                      cur_selector == "@charset" ||
                                      cur_selector == "@namespace"))
         {
             log("Unexpected character '" + std::string(1, css_input[i]) + "' in " + cur_selector, Error);
         }
         if(css_input[i] == '/' && CSSUtils::s_at(css_input,i+1) == '*')
         {
             astatus = PIC; ++i;
             afrom = PIV;
         }
         else if(css_input[i] == '"' || css_input[i] == '\'' ||
                 (css_input[i] == '(' && cur_sub_value == "url") )
         {
             str_char = (css_input[i] == '(') ? ')' : css_input[i];
             cur_string = css_input[i];
             astatus = PINSTR;
             afrom = PIV;
         }
         else if(css_input[i] == '(')
         {
             // function call or an open parenthesis in a calc() expression
             // url() is a special case that should have been handled above
             assert(cur_sub_value != "url");
             // cur_sub_value should contain the name of the function, if any
             cur_sub_value = CSSUtils::trim(cur_sub_value + "(");
             // set current function name and push it onto the stack
             cur_function = cur_sub_value;
             cur_function_arr.push_back(cur_sub_value);
             cur_sub_value_arr.push_back(cur_sub_value);
             cur_sub_value = "";
         }
         else if(css_input[i] == '\\')
         {
             cur_sub_value += unicode(css_input,i);
         }
         else if(css_input[i] == ';' || pn)
         {
             if(cur_selector.substr(0,1) == "@" &&
                at_rules.count(cur_selector.substr(1)) > 0 &&
                at_rules[cur_selector.substr(1)] == PIV)
             {
                 cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
                 astatus = PIS;
                 if(cur_selector == "@charset")
                 {
                      charset = cur_sub_value_arr[0];
                      add_token(CHARSET, charset);
                 }
                 else if(cur_selector == "@import")
                 {
                      std::string aimport = CSSUtils::build_value(cur_sub_value_arr);
                      add_token(IMPORT, aimport);
                      import.push_back(aimport);
                 }
                 else if(cur_selector == "@namespace")
                 {
                     namesp = CSSUtils::implode(" ",cur_sub_value_arr);
                     add_token(NAMESP, namesp);
                 }
                 cur_sub_value_arr.clear();
                 cur_sub_value = "";
                 cur_selector = "";
                 sel_separate = std::vector<int>();
             }
             else
             {
                 astatus = PIP;
             }
         }
         else if (css_input[i] == '!')
         {
             cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
             cur_sub_value = "!";
         }
         else if (css_input[i] == ',' || css_input[i] == ')')
         {
             // store the current subvalue, if any
             cur_sub_value = CSSUtils::trim(cur_sub_value);
             if(cur_sub_value != "")
             {
                 cur_sub_value_arr.push_back(cur_sub_value);
                 cur_sub_value = "";
             }
             bool drop = false;
             if (css_input[i] == ')')
             {
                 if (cur_function_arr.empty())
                 {
                     // No matching open parenthesis, drop this closing one
                     log("Unexpected closing parenthesis, dropping", Warning);
                     drop = true;
                 }
                 else
                 {
                     // Pop function from the stack
                     cur_function_arr.pop_back();
                     cur_function = cur_function_arr.empty() ? "" : cur_function_arr.back();
                 }
             }
             if (!drop) {
                 cur_sub_value_arr.push_back(std::string(1,css_input[i]));
             }
         }
         else if(css_input[i] != '}')
         {
             cur_sub_value += css_input[i];
         }
         if( (css_input[i] == '}' || css_input[i] == ';' || pn) && !cur_selector.empty())
         {
             // End of value: normalize, optimize and store property
             if(cur_at == "")
             {
                 cur_at = "standard";
             }
             // Kill all whitespace
             cur_at = CSSUtils::trim(cur_at);
             cur_selector = CSSUtils::trim(cur_selector);
             cur_value = CSSUtils::trim(cur_value);
             cur_property = CSSUtils::trim(cur_property);
             cur_sub_value = CSSUtils::trim(cur_sub_value);
             cur_property = CSSUtils::strtolower(cur_property);
             if(cur_sub_value != "")
             {
                 cur_sub_value_arr.push_back(cur_sub_value);
                 cur_sub_value = "";
             }
             // Check for leftover open parentheses
             if (!cur_function_arr.empty())
             {
                 std::vector<std::string>::reverse_iterator rit;
                 for (rit = cur_function_arr.rbegin(); rit != cur_function_arr.rend(); ++rit)
                 {
                     log("Closing parenthesis missing for '" + *rit + "', inserting", Warning);
                     cur_sub_value_arr.push_back(")");
                 }
             }
             cur_value = CSSUtils::build_value(cur_sub_value_arr);
             bool valid = (CSSProperties::instance()->contains(cur_property) &&
                           CSSProperties::instance()->levels(cur_property).find(css_level,0) != std::string::npos);
             if(1)
             {
                 //add(cur_at,cur_selector,cur_property,cur_value);
                 add_token(VALUE, cur_value);
             }
             if(!valid)
             {
                 log("Invalid property in " + CSSUtils::strtoupper(css_level) + ": " + cur_property,Warning);
             }
             //Split multiple selectors here if necessary
             cur_property = "";
             cur_sub_value_arr.clear();
             cur_value = "";
         }
         if(css_input[i] == '}')
         {
             explode_selectors();
             add_token(SEL_END, cur_selector);
             astatus = PIS;
             invalid_at = false;
             cur_selector = "";
         }
     }
     else if(!pn)
     {
         cur_sub_value += css_input[i];
         if(CSSUtils::ctype_space(css_input[i]))
         {
             if(CSSUtils::trim(cur_sub_value) != "")
             {
                 cur_sub_value_arr.push_back(CSSUtils::trim(cur_sub_value));
             }
             cur_sub_value = "";
         }
     }
 }
References add_token(), at_rules, CSSUtils::build_value(), CHARSET, charset, CSSProperties::contains(), css_level, CSSUtils::ctype_space(), cur_at, cur_function, cur_function_arr, cur_property, cur_selector, cur_string, cur_sub_value, cur_sub_value_arr, cur_value, Error, explode_selectors(), CSSUtils::implode(), IMPORT, CSSProperties::instance(), is_token(), CSSProperties::levels(), log(), NAMESP, namesp, PIC, PINSTR, PIP, PIS, PIV, property_is_next(), CSSUtils::s_at(), SEL_END, sel_separate, CSSUtils::strtolower(), CSSUtils::strtoupper(), CSSUtils::trim(), unicode(), VALUE, and Warning.
Referenced by parse_css().
property_is_next()
bool CSSParser::property_is_next (std::string istring, int pos) static private
 {
     istring = istring.substr(pos,istring.length()-pos);
     pos = istring.find_first_of(':',0);
     if(pos == std::string::npos)
     {
         return false;
     }
     istring = CSSUtils::strtolower(CSSUtils::trim(istring.substr(0,pos)));
     return CSSProperties::instance()->contains(istring);
 }
References CSSProperties::contains(), CSSProperties::instance(), CSSUtils::strtolower(), and CSSUtils::trim().
Referenced by parseInValue().
record_position()
void CSSParser::record_position (parse_status old_status, parse_status new_status, std::string & css_input, int i, bool force = false) private
 {
     // to reach here old_status must be != new_status
     bool record = false;
     // any state into a  comment
     if (new_status == PIC) record = true;
     // start of a property
     if ((old_status == PIS) && (new_status == PIP)) record = true;
     if ((old_status == PIV) && (new_status == PIP)) record = true;
     // from properties to values or from @charset, @namespace, and @import into values
     if ((old_status == PAT) && (new_status == PIV)) record = true;
     if ((old_status == PIP) && (new_status == PIV)) record = true;
     // starting a new selector
     if ((old_status == PAT) && (new_status == PIS)) record = true;
     if ((old_status == PIV) && (new_status == PIS)) record = true;
     if ((old_status == PIP) && (new_status == PIS)) record = true;
     if (record || force) {
         spos = css_input.find_first_not_of(" \n\t\r\0xb", i);
         sline = line;
         std::cout << "Start Posistion: " << spos << " Start Line: " << sline << std::endl;
         for(int j = i+i; j <= spos; j++)
         {
             if (css_input[j] == '\n') sline++;
         }
     }
 }
References line, PAT, PIC, PIP, PIS, PIV, sline, and spos.
Referenced by parse_css().
reset_parser()
void CSSParser::reset_parser ()
 {
     token_ptr = 0;
     charset = "";
     namesp = "";
     selector_nest_level = 0;
     line = 1;
     import.clear();
     csstokens.clear();
     cur_selector.clear();
     cur_at.clear();
     cur_property.clear();
     cur_function.clear();
     cur_sub_value.clear();
     cur_value.clear();
     cur_string.clear();
     cur_selector.clear();
     sel_separate.clear();
 }
References charset, csstokens, cur_at, cur_function, cur_property, cur_selector, cur_string, cur_sub_value, cur_value, line, namesp, sel_separate, selector_nest_level, and token_ptr.
Referenced by parse_css().
serialize_css()
std::string CSSParser::serialize_css (std::string filename = "", bool tostdout = true)
 {
     if(charset == "" && namesp == "" && import.empty() && csstokens.empty())
     {
         std::cout << "Warning: empty CSS output!" << std::endl;
     }
     std::ofstream file_output;
     if(filename != "")
     {
          file_output.open(filename.c_str(),std::ios::binary);
          if(file_output.bad())
          {
              std::cout << "Error when trying to save the output file!" << std::endl;
              return "";
          }
     }
     std::stringstream output;
     int lvl = 0;
     std::string indent = "";
     for (int i = 0; i < csstokens.size(); ++i)
     {
         switch (csstokens[i].type)
         {
             case CHARSET:
                 output << "@charset " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case IMPORT:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << "@import " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case NAMESP:
                 output << "@namespace " << csstemplate[5] << csstokens[i].data << csstemplate[6];
                 break;
             case AT_START:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << csstemplate[1];
                 lvl++;
                 break;
             case SEL_START:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << csstemplate[3];
                 lvl++;
                 break;
             case PROPERTY:
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent << csstokens[i].data << ":" << csstemplate[5];
                 break;
             case VALUE:
                 output << csstokens[i].data << csstemplate[6];
                 break;
             case SEL_END:
                 lvl--; if (lvl < 0) lvl = 0;
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << indent + csstemplate[7];
                 if(_seeknocomment(i, 1) != AT_END) output << csstemplate[8];
                 break;
             case AT_END:
                 lvl--; if (lvl < 0) lvl = 0;
                 indent = CSSUtils::indent(lvl, csstemplate[0]);
                 output << csstemplate[13] << indent << csstemplate[9];
                 break;
             case COMMENT:
                 output << csstemplate[11] <<  "/*" << csstokens[i].data << "*/" << csstemplate[12];
                 break;
             case CSS_END:
                 break;
         }
     }
     std::string output_string = CSSUtils::trim(output.str());
     if(tostdout)
     {
         std::cout << output_string << "\n";
     }
     if(filename != "")
     {
         file_output << output_string;
         file_output.close();
     }
     return output_string;
 }
References _seeknocomment(), AT_END, AT_START, CHARSET, charset, COMMENT, CSS_END, csstemplate, csstokens, IMPORT, CSSUtils::indent(), NAMESP, namesp, PROPERTY, SEL_END, SEL_START, CSSUtils::trim(), and VALUE.
Referenced by main().
set_csstokens()
void CSSParser::set_csstokens (const std::vector< token > & ntokens)
 {
     csstokens.clear();
     for(int i = 0; i < ntokens.size(); i++)
     {
         token atemp = ntokens[i];
         csstokens.push_back(atemp);
     }
 }
References csstokens.
set_level()
void CSSParser::set_level (std::string level = "CSS3.0")
 {
     if ((level == "CSS1.0") || (level == "CSS2.0") ||
         (level == "CSS2.1") || (level == "CSS3.0"))
     {
         css_level = level;
     }
 }
References css_level.
Referenced by main().
unicode()
std::string CSSParser::unicode (std::string & istring, int & i) private
 {
     ++i;
     std::string add = "";
     bool replaced = false;
     while(i < istring.length() && (CSSUtils::ctype_xdigit(istring[i]) ||
                                    CSSUtils::ctype_space(istring[i])) && add.length()< 6)
     {
         add += istring[i];
         if(CSSUtils::ctype_space(istring[i])) {
             break;
         }
         i++;
     }
     if ((CSSUtils::hexdec(add) > 47 && CSSUtils::hexdec(add) < 58) ||
         (CSSUtils::hexdec(add) > 64 && CSSUtils::hexdec(add) < 91) ||
         (CSSUtils::hexdec(add) > 96 && CSSUtils::hexdec(add) < 123))
     {
         std::string msg = "Replaced unicode notation: Changed \\" + CSSUtils::rtrim(add) + " to ";
         add = static_cast<int>(CSSUtils::hexdec(add));
         msg += add;
         log(msg,Information);
         replaced = true;
     } else {
         add = CSSUtils::trim("\\" + add);
     }
     if ((CSSUtils::ctype_xdigit(istring[i+1]) && CSSUtils::ctype_space(istring[i])
          && !replaced) || !CSSUtils::ctype_space(istring[i]))
     {
         i--;
     }
     if (1) {
         return add;
     }
     return "";
 }
References CSSUtils::ctype_space(), CSSUtils::ctype_xdigit(), CSSUtils::hexdec(), Information, log(), CSSUtils::rtrim(), and CSSUtils::trim().
Referenced by parseInAtBlock(), parseInProperty(), parseInSelector(), and parseInValue().
Member Data Documentation
at_rules
std::map<std::string, parse_status> CSSParser::at_rules private
Referenced by CSSParser(), parseInSelector(), and parseInValue().
charset
std::string CSSParser::charset private
Referenced by get_charset(), parseInValue(), reset_parser(), and serialize_css().
css_level
std::string CSSParser::css_level private
Referenced by CSSParser(), parseInProperty(), parseInValue(), and set_level().
csstemplate
std::vector<std::string> CSSParser::csstemplate private
Referenced by CSSParser(), and serialize_css().
csstokens
std::vector<token> CSSParser::csstokens private
Referenced by _seeknocomment(), add_token(), get_next_token(), reset_parser(), serialize_css(), and set_csstokens().
cur_at
std::string CSSParser::cur_at private
Referenced by parseInAtBlock(), parseInSelector(), parseInValue(), and reset_parser().
cur_function
std::string CSSParser::cur_function private
Referenced by parseInString(), parseInValue(), and reset_parser().
cur_function_arr
std::vector<std::string> CSSParser::cur_function_arr private
Referenced by parse_css(), and parseInValue().
cur_property
std::string CSSParser::cur_property private
Referenced by parseInProperty(), parseInString(), parseInValue(), and reset_parser().
cur_selector
std::string CSSParser::cur_selector private
Referenced by parseInProperty(), parseInSelector(), parseInString(), parseInValue(), and reset_parser().
cur_string
std::string CSSParser::cur_string private
Referenced by parseInSelector(), parseInString(), parseInValue(), and reset_parser().
cur_sub_value
std::string CSSParser::cur_sub_value private
Referenced by parseInString(), parseInValue(), and reset_parser().
cur_sub_value_arr
std::vector<std::string> CSSParser::cur_sub_value_arr private
Referenced by parse_css(), and parseInValue().
cur_value
std::string CSSParser::cur_value private
Referenced by parseInValue(), and reset_parser().
import
std::vector<std::string> CSSParser::import private
line
int CSSParser::line private
Referenced by log(), parse_css(), record_position(), and reset_parser().
logs
std::map<int, std::vector<message> > CSSParser::logs private
Referenced by get_logs(), and log().
namesp
std::string CSSParser::namesp private
Referenced by get_namespace(), parseInValue(), reset_parser(), and serialize_css().
sel_separate
std::vector<int> CSSParser::sel_separate private
Referenced by explode_selectors(), parseInSelector(), parseInValue(), and reset_parser().
selector_nest_level
int CSSParser::selector_nest_level private
Referenced by add_token(), parse_css(), and reset_parser().
sline
int CSSParser::sline private
Referenced by add_token(), and record_position().
spos
int CSSParser::spos private
Referenced by add_token(), and record_position().
token_ptr
int CSSParser::token_ptr private
Referenced by get_next_token(), and reset_parser().
token_type_names
std::vector<std::string> CSSParser::token_type_names private
Referenced by CSSParser(), and get_type_name().
tokens
std::string CSSParser::tokens private
Referenced by CSSParser(), and is_token().