CSS Parser: CSSProperties::contains
contains
CSSProperties
instance
levels
m_all_properties
m_instance
contains()
bool CSSProperties::contains (std::string pname)
 {
     return m_all_properties.count(pname) == 1;
 }
References m_all_properties.
Referenced by levels(), CSSParser::parseInProperty(), CSSParser::parseInValue(), and CSSParser::property_is_next().