CSS Parser: CSSProperties::instance
contains
CSSProperties
instance
levels
m_all_properties
m_instance
instance()
CSSProperties * CSSProperties::instance () static
 {
     if (m_instance == 0) {
         m_instance = new CSSProperties();
     }
     return m_instance;
 }
References CSSProperties(), and m_instance.
Referenced by CSSParser::parseInProperty(), CSSParser::parseInValue(), and CSSParser::property_is_next().