CSS Parser: CSSUtils::chartolower
build_value
char2str
char2str
chartolower
chartoupper
ctype_alpha
ctype_digit
ctype_space
ctype_xdigit
escaped
explode
file_exists
file_get_contents
hexdec
implode
in_char_arr
in_str_array
indent
ltrim
rtrim
rtrim
s_at
str_replace
strtolower
strtoupper
trim
chartolower()
char CSSUtils::chartolower (const char c) static
 {
     switch(c)
     {
         case 'A': return 'a';
         case 'B': return 'b';
         case 'C': return 'c';
         case 'D': return 'd';
         case 'E': return 'e';
         case 'F': return 'f';
         case 'G': return 'g';
         case 'H': return 'h';
         case 'I': return 'i';
         case 'J': return 'j';
         case 'K': return 'k';
         case 'L': return 'l';
         case 'M': return 'm';
         case 'N': return 'n';
         case 'O': return 'o';
         case 'P': return 'p';
         case 'Q': return 'q';
         case 'R': return 'r';
         case 'S': return 's';
         case 'T': return 't';
         case 'U': return 'u';
         case 'V': return 'v';
         case 'W': return 'w';
         case 'X': return 'x';
         case 'Y': return 'y';
         case 'Z': return 'z';
         default: return c;
     }
 }
Referenced by ctype_alpha(), ctype_xdigit(), and strtolower().